---
kind: pipeline
name: default
steps:
  - name: Prepare docker buildx
    image: thegeeklab/drone-docker-buildx
    privileged: true
    commands:
      - sleep 5
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    volumes:
      - name: dockersock
        path: /var/run

  # auto_tag is not working for some reason
  - name: Docker buildx arm64 master
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      username: veselahouba
      password:
        from_secret: VH_DOCKER_PASSWORD
      repo: veselahouba/${DRONE_REPO_NAME/_/-}
      platforms:
        - linux/amd64
        - linux/arm64/v8
      auto_tag: true
    when:
      branch:
        - master

  - name: Docker buildx arm64 branch
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      username: veselahouba
      password:
        from_secret: VH_DOCKER_PASSWORD
      repo: veselahouba/${DRONE_REPO_NAME/_/-}
      platforms:
        - linux/amd64
        - linux/arm64/v8
      tags: ${DRONE_BRANCH}
    when:
      branch:
        exclude:
          - master

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        {{#success build.status}}
          Publish for `{{repo.name}}/{{build.ref}}` succeeded.
          {{build.link}}
        {{else}}
          Publish for `{{repo.name}}/{{build.ref}}` failed.
          {{build.link}}
        {{/success}}
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      status:
        - success
        - failure

services:
  - name: dind
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
