---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages which are usually present
      apt:
        update_cache: true
        name:
          - locales
          - tzdata
          - apt-transport-https

    - name: Create dirs missing in docker image
      file:
        path: /run/lock/
        state: directory
        mode: 0755

    - name: Add machines to /etc/hosts
      shell: echo "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}" >> /etc/hosts
      with_items: "{{ groups['all'] }}"
      changed_when: false
